source "http://rubygems.org"

gem 'mongrel', '1.2.0.pre2'
gem 'pg', '0.9.0'
gem 'mysql2', '0.3.11'
gem 'sinatra', '1.3.3', :require => 'sinatra/base'
gem 'activerecord', '3.0.0', :require => 'active_record'
gem 'nokogiri', '1.4.3.1'
gem 'haml', '3.0.17'
#gem 'errand', '0.7.2'
gem 'yajl-ruby', '0.7.7'
#gem 'levenshtein19', :require => 'levenshtein'
gem 'amatch', '0.2.10'
gem 'rmagick', '2.13.1', :require => 'RMagick'
gem 'rugged', '0.16.0'
gem 'memcache-client', '1.8.5', :require => 'memcache'
gem 'rack-throttle', '0.3.0'
